server:
  port: 8082

spring:
  application:
    name: ms-mapeo
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ms_mapeo}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
        format_sql: true
        jdbc:
          time_zone: UTC
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

logging:
  level:
    org.hibernate.SQL: DEBUG

springdoc:
  api-docs:
    path: /api/mapeo/v3/api-docs

security:
  jwt:
    jwks-url: ${JWK_SET_URI:http://ms-usuarios:8081/.well-known/jwks.json}
