server:
  port: 8080

spring:
  application:
    name: ms-bff
  cloud:
    gateway:
      mvc:
        routes:
          - id: ms-usuarios
            uri: http://ms-usuarios:8081
            predicates:
              - Path=/api/usuarios/**
          - id: ms-mapeo
            uri: http://ms-mapeo:8082
            predicates:
              - Path=/api/mapeo/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER:http://localhost:8081}
          jwk-set-uri: ${JWK_SET_URI:http://localhost:8081/.well-known/jwks.json}


# Resilience4j
resilience4j.circuitbreaker:
  instances:
    backendA:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 5
      waitDurationInOpenState: 50s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html
    urls:
      - name: BFF Gateway
        url: /v3/api-docs
      - name: ms-usuarios
        url: /api/usuarios/v3/api-docs
      - name: ms-mapeo
        url: /api/mapeo/v3/api-docs

# OAuth2 Resource Server (JWT)

