server:
  port: 8080

spring:
  application:
    name: ms-bff
  cloud:
    gateway:
      mvc:
        routes:
          - id: ms-usuarios
            uri: http://krakend:8080
            predicates:
              - Path=/api/usuarios/**
          - id: ms-mapeo
            uri: http://krakend:8080
            predicates:
              - Path=/api/mapeo/**

# Resilience4j
resilience4j.circuitbreaker:
  instances:
    backendA:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 5
      waitDurationInOpenState: 50s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
