apiVersion: v1
kind: Service
metadata:
  name: ms-bff
  namespace: plataforma-incendios
  labels:
    app: ms-bff
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: ms-bff
