apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: plataforma-incendios
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgis/postgis:16-3.4-alpine
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_INITDB_ARGS
              value: "-c shared_buffers=256MB"
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgres-db-data
              mountPath: /var/lib/postgresql/data
            - name: postgres-init-sql
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: postgres-db-data
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: postgres-init-sql
          configMap:
            name: postgres-init-configmap
